# netlify.toml

# This tells Netlify where your serverless functions are located.
[build]
  functions = "netlify/functions"

# This specifies the bundler to use for your functions.
[functions]
  node_bundler = "esbuild"